apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  labels:
    {{- include "deegree-inspire.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "deegree-inspire.selectorLabels" . | nindent 13 }}
        spec:
          serviceAccountName: {{ .Release.Name }}-serviceaccount
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 13 }}
          containers:
          - name: {{ .Release.Name }}-container
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 15 }}
            resources:
              {{- toYaml .Values.resources | nindent 15 }}
            readinessProbe:
              exec:
                command:
                - echo readinessProbe
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              exec:
                command:
                - echo livenessProbe
              initialDelaySeconds: 15
              periodSeconds: 20
            volumeMounts:
            - mountPath: /tmp/deegree_response
              name: {{ .Release.Name }}-volume
            command:
            - /bin/sh
            - -c
            - date;
              wget {{ .Values.cronjob.ingressUrl }}/deegree-inspire/services/inspire_us_schulstandorte_download?SERVICE=WFS\&REQUEST=GetFeature\&VERSION=2.0.0\&Typenames=us-govserv:GovernmentalService\&Count=1  -O temp.gml;
              wget {{ .Values.cronjob.ingressUrl }}/deegree-inspire/services/inspire_us_schulstandorte_view?service=WMS\&request=GetMap\&VERSION=1.3.0\&CRS=EPSG:25833\&LAYERS=US.PrimaryEducation\&STYLES=\&BBOX=259000,5944624,271000,5955747\&FORMAT=image/png\&WIDTH=720\&HEIGHT=460  -O temp.gml;
          restartPolicy: OnFailure
          volumes:
          - name: {{ .Release.Name }}-volume
            emptyDir: {}